# typed: false
# frozen_string_literal: true

AcmeSelectorSurfaceConfig = Data.define(
  :surface,
  :principal_class,
  :token_class,
  :rp_account_class,
  :rp_account_foreign_key,
  :identity_class,
  :identity_state_class,
  :account_class,
  :account_identity_association,
  :account_assignment_class,
  :account_assignment_account_key,
  :account_assignment_identity_key,
  :account_moniker,
  :collective_class,
  :collective_name,
  :unit_class,
  :unit_collective_association,
  :membership_class,
  :membership_kind_class,
  :membership_state_class,
  :membership_account_association,
  :membership_collective_association,
  :membership_unit_association,
  :requires_avatar,
  :account_title,
  :collective_title,
)

AcmeSelectorSurfaceConfig::CONFIGS = {
  app: AcmeSelectorSurfaceConfig.new(
    surface: :app,
    principal_class: ::Client,
    token_class: ::ClientToken,
    rp_account_class: ::ClientAccount,
    rp_account_foreign_key: :user_id,
    identity_class: ::ClientIdentity,
    identity_state_class: ::ClientIdentityState,
    account_class: ::ClientPersona,
    account_identity_association: :client_identity,
    account_assignment_class: ::PersonaAssignment,
    account_assignment_account_key: :persona_id,
    account_assignment_identity_key: :client_identity_id,
    account_moniker: "Default Persona",
    collective_class: ::Enterprise,
    collective_name: "Personal Organization",
    unit_class: ::EnterpriseUnit,
    unit_collective_association: :enterprise,
    membership_class: ::PersonaMembership,
    membership_kind_class: ::PersonaMembershipKind,
    membership_state_class: ::PersonaMembershipState,
    membership_account_association: :persona,
    membership_collective_association: :enterprise,
    membership_unit_association: :enterprise_unit,
    requires_avatar: true,
    account_title: "Persona01",
    collective_title: "Org01",
  ),
  com: AcmeSelectorSurfaceConfig.new(
    surface: :com,
    principal_class: ::Visitor,
    token_class: ::VisitorToken,
    rp_account_class: ::VisitorAccount,
    rp_account_foreign_key: :visitor_id,
    identity_class: ::VisitorIdentity,
    identity_state_class: ::VisitorIdentityState,
    account_class: ::Individual,
    account_identity_association: :visitor_identity,
    account_assignment_class: ::IndividualAssignment,
    account_assignment_account_key: :individual_id,
    account_assignment_identity_key: :visitor_identity_id,
    account_moniker: "Default Individual",
    collective_class: ::Company,
    collective_name: "Personal Company",
    unit_class: ::CompanyUnit,
    unit_collective_association: :company,
    membership_class: ::IndividualMembership,
    membership_kind_class: ::IndividualMembershipKind,
    membership_state_class: ::IndividualMembershipState,
    membership_account_association: :individual,
    membership_collective_association: :company,
    membership_unit_association: :company_unit,
    requires_avatar: false,
    account_title: "Indiv01",
    collective_title: "Org01",
  ),
  org: AcmeSelectorSurfaceConfig.new(
    surface: :org,
    principal_class: ::Operator,
    token_class: ::OperatorToken,
    rp_account_class: ::OperatorAccount,
    rp_account_foreign_key: :staff_id,
    identity_class: ::OperatorIdentity,
    identity_state_class: ::OperatorIdentityState,
    account_class: ::Agent,
    account_identity_association: :operator_identity,
    account_assignment_class: ::AgentAssignment,
    account_assignment_account_key: :agent_id,
    account_assignment_identity_key: :operator_identity_id,
    account_moniker: "Default Agent",
    collective_class: ::Bureau,
    collective_name: "Personal Bureau",
    unit_class: ::BureauUnit,
    unit_collective_association: :bureau,
    membership_class: ::AgentMembership,
    membership_kind_class: ::AgentMembershipKind,
    membership_state_class: ::AgentMembershipState,
    membership_account_association: :agent,
    membership_collective_association: :bureau,
    membership_unit_association: :bureau_unit,
    requires_avatar: false,
    account_title: "Agent01",
    collective_title: "Org01",
  ),
}.freeze
