// The Warp control-plane settings screen, shared by the three Warp surfaces.
//
// It sits next to `WarpDashboard` because it is the other half of the same control plane: the two
// screens link to each other and are reached from the same landing.
//
// Every href is generated by Rails and arrives resolved, so this component never composes a path
// from a surface name. The rows are a document visit rather than an Inertia one because sign-out
// leaves this surface, and `NavList` already defaults to that.
import NavList from "@/components/ui/NavList";
import Page from "@/components/ui/Page";

export type WarpSettingsLink = { label: string; href: string };

export type WarpSettingsProps = {
  title: string;
  heading: string;
  description: string;
  links: WarpSettingsLink[];
};

export default function WarpSettings({ heading, description, links }: WarpSettingsProps) {
  return (
    <Page
      title={heading}
      description={description}
    >
      <NavList
        items={links}
        label={heading}
      />
    </Page>
  );
}
