// The signed-in Warp landing, shared by the three Warp surfaces.
//
// Every href is generated by Rails and arrives resolved, so this component never composes a path
// from a surface name.
import Card from "@/components/ui/Card";
import Page from "@/components/ui/Page";

export type WarpDashboardLink = { label: string; href: string };

export type WarpDashboardSection = {
  title: string;
  links: WarpDashboardLink[];
};

export type WarpDashboardProps = {
  title: string;
  heading: string;
  description: string;
  sections: WarpDashboardSection[];
};

export default function WarpDashboard({ heading, description, sections }: WarpDashboardProps) {
  return (
    <Page
      title={heading}
      description={description}
      width="wide"
    >
      {sections.map((section) => (
        <Card
          key={section.title}
          heading={section.title}
        >
          <ul className="flex flex-col gap-1">
            {section.links.map((link) => (
              <li key={link.href}>
                <a
                  href={link.href}
                  className="ui-text-link text-base text-fg underline underline-offset-4 hover:underline"
                >
                  {link.label}
                </a>
              </li>
            ))}
          </ul>
        </Card>
      ))}
    </Page>
  );
}
