// The first step of an email or telephone registration: submit the identifier and the consents.
//
// The form posts as an ordinary document, exactly as the ERB it replaces did, because the server
// answers a rejected submission by re-rendering this page with 422 and answers an accepted one with
// a redirect into the OTP step. Every label, description and URL arrives finished from the server;
// the Turnstile widget writes the token into the hidden field the form submits.
import Button from "@/components/ui/Button";
import Checkbox from "@/components/ui/Checkbox";
import TextField from "@/components/ui/TextField";
import TurnstileWidget, { type TurnstileWidgetProps } from "@/features/turnstile/TurnstileWidget";

import { csrfToken } from "./csrf";

export type ContactSignUpCheckbox = {
  name: string;
  label: string;
  description: string | null;
};

export type ContactSignUpFormProps = {
  title: string;
  /** Endpoint the form posts to, generated by the server. */
  action: string;
  /** Rails parameter scope, e.g. "client_email". */
  scope: string;
  field: {
    name: string;
    label: string;
    type: "email" | "tel";
    autocomplete: string;
    /** The server-provided value to restore after a rejected submission. */
    value?: string;
  };
  checkboxes: ContactSignUpCheckbox[];
  /** Heading shown above the validation errors, or null when there are none. */
  error_heading: string | null;
  errors: string[];
  turnstile: TurnstileWidgetProps;
  submit_label: string;
  links: { key: string; label: string; href: string }[];
};

export default function ContactSignUpForm({
  title,
  action,
  scope,
  field,
  checkboxes,
  error_heading: errorHeading,
  errors,
  turnstile,
  submit_label: submitLabel,
  links,
}: ContactSignUpFormProps) {
  return (
    <section className="flex flex-col gap-6">
      <h2 className="text-xl font-semibold text-fg">{title}</h2>

      <form
        action={action}
        method="post"
        data-turbo="false"
        className="flex flex-col gap-4"
      >
        <input
          type="hidden"
          name="authenticity_token"
          value={csrfToken()}
        />

        {errorHeading ? (
          <div
            role="alert"
            className="flex flex-col gap-2 rounded-md border border-danger bg-surface p-3 text-sm
              text-danger"
          >
            <h3 className="font-semibold">{errorHeading}</h3>
            <ul
              role="list"
              className="flex flex-col gap-1 pl-4 list-disc"
            >
              {errors.map((message) => (
                <li key={message}>{message}</li>
              ))}
            </ul>
          </div>
        ) : null}

        <TextField
          label={field.label}
          type={field.type}
          name={`${scope}[${field.name}]`}
          autoComplete={field.autocomplete}
          defaultValue={field.value ?? ""}
          isRequired
          validationBehavior="native"
        />

        {checkboxes.map((checkbox) => (
          <div
            key={checkbox.name}
            className="flex flex-col gap-1"
          >
            {/* Rails reads the unchecked value from the paired hidden field, as `form.check_box` did. */}
            <input
              type="hidden"
              name={`${scope}[${checkbox.name}]`}
              value="0"
            />
            <Checkbox
              name={`${scope}[${checkbox.name}]`}
              value="1"
            >
              <span className="flex flex-col">
                <span>{checkbox.label}</span>
                {checkbox.description ? (
                  <span className="text-xs text-fg-muted">{checkbox.description}</span>
                ) : null}
              </span>
            </Checkbox>
          </div>
        ))}

        <TurnstileWidget {...turnstile} />

        <Button type="submit">{submitLabel}</Button>
      </form>

      {links.map((link) => (
        <p
          key={link.key}
          className="text-sm"
        >
          <a
            href={link.href}
            className="text-fg underline-offset-4 hover:underline"
          >
            {link.label}
          </a>
        </p>
      ))}
    </section>
  );
}
