// The OTP step of an email or telephone registration.
//
// The code itself never crosses the boundary: the server sends only what the page shows — the
// heading, the "we sent you a code" copy, the delivery help, and any validation message from the
// previous attempt. The form submits as an ordinary document with the verb the route expects,
// because the server answers a wrong code by re-rendering this page with 422 or 429 and a correct
// one with a redirect into the next step.
import Button from "@/components/ui/Button";
import TextField from "@/components/ui/TextField";
import TurnstileWidget, { type TurnstileWidgetProps } from "@/features/turnstile/TurnstileWidget";

import { csrfToken } from "./csrf";

export type OtpVerificationFormProps = {
  title: string;
  description: string;
  /** Endpoint the form patches, generated by the server. */
  action: string;
  /** Rails parameter scope, e.g. "client_email". */
  scope: string;
  code_label: string;
  code_placeholder: string;
  submit_label: string;
  delivery_help: string;
  /** Interactive challenge required by email registration checkpoints. */
  turnstile?: TurnstileWidgetProps | null;
  /** Heading shown above the validation errors, or null when there are none. */
  error_heading: string | null;
  errors: string[];
  return_link: { label: string; href: string };
};

export default function OtpVerificationForm({
  title,
  description,
  action,
  scope,
  code_label: codeLabel,
  code_placeholder: codePlaceholder,
  submit_label: submitLabel,
  delivery_help: deliveryHelp,
  turnstile,
  error_heading: errorHeading,
  errors,
  return_link: returnLink,
}: OtpVerificationFormProps) {
  return (
    <section className="flex flex-col gap-6">
      <h1 className="text-2xl font-bold text-fg">{title}</h1>
      <p className="text-sm text-fg-muted">{description}</p>

      <form
        action={action}
        method="post"
        data-turbo="false"
        className="flex flex-col gap-4"
      >
        <input
          type="hidden"
          name="_method"
          value="patch"
        />
        <input
          type="hidden"
          name="authenticity_token"
          value={csrfToken()}
        />

        {errors.length > 0 ? (
          <div
            role="alert"
            className="flex flex-col gap-2 rounded-md border border-danger bg-surface p-3 text-sm
              text-danger"
          >
            {/* v8 ignore next -- a heading is only sent when the list is non-empty */}
            {errorHeading ? <h2 className="font-semibold">{errorHeading}</h2> : null}
            <ul className="flex flex-col gap-1 pl-4 list-disc">
              {errors.map((message) => (
                <li key={message}>{message}</li>
              ))}
            </ul>
          </div>
        ) : null}

        <TextField
          label={codeLabel}
          name={`${scope}[pass_code]`}
          placeholder={codePlaceholder}
          // oxlint-disable-next-line jsx-a11y/no-autofocus -- the ERB field carried autofocus.
          autoFocus
          autoComplete="one-time-code"
          inputMode="numeric"
          pattern="[0-9]*"
        />

        {turnstile ? (
          <TurnstileWidget
            key={turnstile.challenge_id ?? "otp"}
            {...turnstile}
          />
        ) : null}

        <Button type="submit">{submitLabel}</Button>
      </form>

      <p className="text-sm text-fg-muted">{deliveryHelp}</p>

      <p className="text-sm">
        <a
          href={returnLink.href}
          className="text-fg underline-offset-4 hover:underline"
        >
          {returnLink.label}
        </a>
      </p>
    </section>
  );
}
