// The confirmation step of a social sign-up: the provider identity is unknown here, so the visitor
// has to confirm that a new identity is what they want before anything is created.
//
// The Turnstile challenge is bound to this ceremony by the server, which passes the action and the
// ticket's public id as cdata and verifies both against the token it receives back.
import Button from "@/components/ui/Button";
import Checkbox from "@/components/ui/Checkbox";
import Page from "@/components/ui/Page";
import TurnstileWidget, { type TurnstileWidgetProps } from "@/features/turnstile/TurnstileWidget";

import { csrfToken } from "./csrf";

export type SocialSignUpConfirmationProps = {
  title: string;
  unregistered: string;
  create_identity: string;
  no_merge: string;
  cancel_if_wrong: string;
  confirm_label: string;
  submit_label: string;
  cancel_label: string;
  /** Endpoint for both the confirmation and the cancellation, generated by the server. */
  action: string;
  checkpoint_version: number;
  turnstile: TurnstileWidgetProps;
};

export default function SocialSignUpConfirmation({
  title,
  unregistered,
  create_identity: createIdentity,
  no_merge: noMerge,
  cancel_if_wrong: cancelIfWrong,
  confirm_label: confirmLabel,
  submit_label: submitLabel,
  cancel_label: cancelLabel,
  action,
  checkpoint_version: checkpointVersion,
  turnstile,
}: SocialSignUpConfirmationProps) {
  return (
    <Page
      title={title}
      description={unregistered}
      width="narrow"
    >
      <p className="text-base text-fg-muted">{createIdentity}</p>
      <p className="text-base text-fg-muted">{noMerge}</p>
      <p className="text-base text-fg-muted">{cancelIfWrong}</p>

      <form
        action={action}
        method="post"
        data-turbo="false"
        className="flex flex-col gap-4"
      >
        <input
          type="hidden"
          name="_method"
          value="patch"
        />
        <input
          type="hidden"
          name="authenticity_token"
          value={csrfToken()}
        />

        <TurnstileWidget {...turnstile} />

        <input
          type="hidden"
          name="checkpoint_version"
          value={checkpointVersion}
        />

        <Checkbox
          name="confirm_new_social_identity"
          value="1"
          isRequired
          validationBehavior="native"
        >
          {confirmLabel}
        </Checkbox>

        <Button type="submit">{submitLabel}</Button>
      </form>

      <form
        action={action}
        method="post"
        data-turbo="false"
      >
        <input
          type="hidden"
          name="_method"
          value="delete"
        />
        <input
          type="hidden"
          name="authenticity_token"
          value={csrfToken()}
        />
        <Button
          type="submit"
          variant="secondary"
        >
          {cancelLabel}
        </Button>
      </form>
    </Page>
  );
}
