# typed: false
# frozen_string_literal: true

require "json"
require "open3"
require "pathname"
require "yaml"

# Reads and writes the technical-debt baseline for the Umaxica architecture cops.
#
# Two artifacts are produced from one measurement so they can never disagree:
#
# * `.rubocop_todo.yml` - per-cop `Exclude` lists, so `bin/rubocop` stays green while rejecting any
#   violation in a file that is not already in debt.
# * `.rubocop/architecture_baseline.yml` - per-file offense counts, so
#   `test/tooling/architecture_baseline_test.rb` also rejects a new violation added to a file that is
#   already in debt. Counts may only go down.
module ArchitectureBaseline
  ROOT = Pathname.new(__dir__).join("..").expand_path
  COPS = %w(Umaxica/NoConcernInclusionHooks Umaxica/ExplicitMethodVisibility).freeze
  COUNTS_PATH = ROOT.join(".rubocop/architecture_baseline.yml")
  TODO_PATH = ROOT.join(".rubocop_todo.yml")
  MEASURE_CONFIG_PATH = ROOT.join(".rubocop/architecture_measure.yml")
  HEADER = <<~YAML
    # Generated by `bin/rails architecture:baseline`. Do not edit by hand.
    #
    # Technical-debt inventory for the Umaxica architecture cops, not an error suppression
    # mechanism: entries may only be removed. See
    # docs/architecture/method-visibility-and-concerns.md.
  YAML

  MeasurementError = Class.new(StandardError)

  class << self
    public

    # Returns { cop_name => { relative_path => offense_count } } for the whole repository.
    def measure
      run_measurement
    end

    def recorded
      YAML.load_file(COUNTS_PATH, aliases: false)
    end

    def write(counts)
      sorted = counts.to_h { |cop, files| [cop, files.sort.to_h] }
      COUNTS_PATH.write(HEADER + sorted.to_yaml)
      TODO_PATH.write(HEADER + todo_body(sorted))
    end

    private

    def run_measurement
      stdout, status = Open3.capture2(
        { "RUBOCOP_CACHE_ROOT" => ROOT.join("tmp/rubocop_cache").to_s },
        "bundle", "exec", "rubocop", "--config", MEASURE_CONFIG_PATH.to_s,
        "--only", COPS.join(","), "--format", "json", "--no-color",
        chdir: ROOT.to_s,
      )
      raise(MeasurementError, "rubocop exited with #{status.exitstatus} and no parsable output") if stdout.empty?

      report = JSON.parse(stdout)
      counts = COPS.index_with { {} }
      report.fetch("files").each do |file|
        file.fetch("offenses").each do |offense|
          cop = offense.fetch("cop_name")
          next unless counts.key?(cop)

          counts[cop][file.fetch("path")] = counts[cop].fetch(file.fetch("path"), 0) + 1
        end
      end
      counts
    end

    def todo_body(counts)
      counts.map { |cop, files|
        excludes = files.keys.map { |path| "    - #{path.inspect}\n" }.join
        "\n#{cop}:\n  Exclude:\n#{excludes}"
      }.join
    end
  end
end
