#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/umaxica/valkey/error"
require_relative "../lib/umaxica/valkey/configuration_error"
require_relative "../lib/umaxica/valkey/test_run_scope"

run_id = ENV.fetch("VALKEY_NAMESPACE_RUN_ID")
action = ARGV.fetch(0)

case action
when "claim"
  Umaxica::Valkey::TestRunScope.claim!(run_id)
when "release"
  Umaxica::Valkey::TestRunScope.release!(run_id)
else
  abort("usage: scripts/test-valkey-run-scope claim|release")
end
