import NavList from "@/components/ui/NavList";
import Page from "@/components/ui/Page";
import CeremonyCancellation, {
  type CeremonyCancellationProps,
} from "@/features/auth/CeremonyCancellation";

// Shown when the actor holds no step-up factor at all: register one before the ceremony can run.
//
// Only the factors still missing are listed, and each link is generated by the server because one
// of them lives on another host. No earlier step-up state exists, so there is no Back: the only exit
// is cancelling the ceremony.
import type { VerificationMethodLink } from "./types";

export type VerificationSetupProps = {
  title: string;
  heading: string;
  description: string;
  cancel: CeremonyCancellationProps;
  methods: VerificationMethodLink[];
};

export default function VerificationSetup({
  heading,
  description,
  cancel,
  methods,
}: VerificationSetupProps) {
  return (
    <Page
      title={heading}
      description={description}
      width="narrow"
    >
      <NavList items={methods} />
      <CeremonyCancellation {...cancel} />
    </Page>
  );
}
